### ISSUE TITLE
Any usage guidance for this docker?

### ISSUE THREAD

**Issue by mcao2** [aofei/docker-cloudflare-warp#1]
Hello @aofei , this repo and its associated docker looks cool and interesting. I'm trying to use warp-cli in a docker container, do you have docs/guidance regarding this? Thank you!

**Comment by aofei** [comment]
This's a base image for my personal use. So there's no compatibility guarantee against it. (It actually seems to be pretty stable though.)

For example, I would use it to build some SOCKS/HTTP proxies.

```sh
$ tree
.
├── Dockerfile
└── rootfs
    └── etc
        ├── services.d
        │   ├── danted
        │   │   └── run
        │   └── squid
        │       └── run
        └── sockd.conf

5 directories, 4 files

$ cat Dockerfile
FROM aofei/cloudflare-warp

COPY rootfs/ /

RUN apk add --no-cache dante-server squid

EXPOSE 1080 3128

$ cat rootfs/etc/services.d/danted/run
#!/usr/bin/with-contenv sh
echo "[$(basename "$(pwd)")] starting..."
set -e
s6-svwait -U /run/service/cloudflare-warp
exec 2>&1 /usr/sbin/sockd

$ cat rootfs/etc/services.d/squid/run
#!/usr/bin/with-contenv sh
echo "[$(basename "$(pwd)")] starting..."
set -e
s6-svwait -U /run/service/cloudflare-warp
exec 2>&1 /usr/sbin/squid --foreground

$ cat rootfs/etc/sockd.conf
internal: eth0 port=1080
external: CloudflareWARP
clientmethod: none
socksmethod: none
client pass {
	from: 0/0 to: 0/0
}
socks pass {
	from: 0/0 to: 0/0
	command: bind connect udpassociate bindreply udpreply
}

$ docker build --tag cloudflare-warp-proxy .
...
$ docker run --detach --restart always \
	--name cloudflare-warp-proxy \
	--publish 1080:1080 \
	--publish 3128:3128 \
	--privileged \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--sysctl net.ipv6.conf.all.forwarding=1 \
	cloudflare-warp-proxy
...
$ curl -x socks5h://127.0.0.1:1080 https://ipinfo.io
...
$ curl -x http://127.0.0.1:3128 https://ipinfo.io
...
```

**Comment by mcao2** [comment]
> This's a base image for my personal use. So there's no compatibility guarantee against it. (It actually seems to be pretty stable though.)
> 
> For example, I would use it to build some SOCKS/HTTP proxies.
> 
> ```shell
> $ tree
> .
> ├── Dockerfile
> └── rootfs
>     └── etc
>         ├── services.d
>         │   ├── danted
>         │   │   └── run
>         │   └── squid
>         │       └── run
>         └── sockd.conf
> 
> 5 directories, 4 files
> 
> $ cat Dockerfile
> FROM aofei/cloudflare-warp
> 
> COPY rootfs/ /
> 
> RUN apk add --no-cache dante-server squid
> 
> EXPOSE 1080 3128
> 
> $ cat rootfs/etc/services.d/danted/run
> #!/usr/bin/with-contenv sh
> echo "[$(basename "$(pwd)")] starting..."
> set -e
> s6-svwait -U /run/service/cloudflare-warp
> exec 2>&1 /usr/sbin/sockd
> 
> $ cat rootfs/etc/services.d/squid/run
> #!/usr/bin/with-contenv sh
> echo "[$(basename "$(pwd)")] starting..."
> set -e
> s6-svwait -U /run/service/cloudflare-warp
> exec 2>&1 /usr/sbin/squid --foreground
> 
> $ cat rootfs/etc/sockd.conf
> internal: eth0 port=1080
> external: CloudflareWARP
> clientmethod: none
> socksmethod: none
> client pass {
> 	from: 0/0 to: 0/0
> }
> socks pass {
> 	from: 0/0 to: 0/0
> 	command: bind connect udpassociate bindreply udpreply
> }
> 
> $ docker build --tag cloudflare-warp-proxy .
> ...
> $ docker run --detach --restart always \
> 	--name cloudflare-warp-proxy \
> 	--publish 1080:1080 \
> 	--publish 3128:3128 \
> 	--privileged \
> 	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
> 	--sysctl net.ipv6.conf.all.forwarding=1 \
> 	cloudflare-warp-proxy
> ...
> $ curl -x socks5h://127.0.0.1:1080 https://ipinfo.io
> ...
> $ curl -x http://127.0.0.1:3128 https://ipinfo.io
> ...
> ```

Thank you so much! This is what I intended to do in the end! 🎉

**Comment by foremtehan** [comment]
mine not working :(

```curl: (7) Unable to receive initial SOCKS5 response.```

![image](https://github.com/aofei/docker-cloudflare-warp/assets/53290883/e159e12c-69e9-4ac4-92d7-15985ba2ab50)
